<Project>

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <Version>0.1.0-alpha.1</Version>
        <Authors>qian-o</Authors>
        <Description>An unofficial WinUI 3 adaptation of AvalonDock for model-driven docking workspaces.</Description>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/qian-o/WinUI.AvalonDock</RepositoryUrl>
        <PackageProjectUrl>https://github.com/qian-o/WinUI.AvalonDock</PackageProjectUrl>
        <PackageTags>WinUI;WinUI3;AvalonDock;Docking</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageOutputPath>$(MSBuildThisFileDirectory)..\.nuget</PackageOutputPath>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Include="$(MSBuildThisFileDirectory)..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)..\THIRD-PARTY-NOTICES.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
