<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateLibraryLayout>true</GenerateLibraryLayout>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dirkster.AvalonDock.Core" />
        <PackageReference Include="Microsoft.WindowsAppSDK" />
        <EmbeddedResource Update="Properties/Resources*.resx">
            <ManifestResourceName>AvalonDock.Properties.%(Filename)</ManifestResourceName>
        </EmbeddedResource>
    </ItemGroup>

    <Import Project="..\..\NuGet.Packaging.props" />

</Project>
