<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>WinUI.AvalonDock.Experiments.Docking</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Dirkster.AvalonDock.Serializer.Xml" />
        <PackageReference Include="Dirkster.AvalonDock.Mvvm" />
    </ItemGroup>
</Project>
