// Based on Dirkster.AvalonDock v5.0.0 (MS-PL), Properties/Resources.Designer.cs.
// Upstream: 408dc2896e2f41f3bb79a15207f160edee8a6792.
#nullable disable
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonDock.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvalonDock.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Files.
        /// </summary>
        public static string Active_Files {
            get {
                return ResourceManager.GetString("Active_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Tool Windows.
        /// </summary>
        public static string Active_ToolWindows {
            get {
                return ResourceManager.GetString("Active_ToolWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Hide.
        /// </summary>
        public static string Anchorable_AutoHide {
            get {
                return ResourceManager.GetString("Anchorable_AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Hide.
        /// </summary>
        public static string Anchorable_BtnAutoHide_Hint {
            get {
                return ResourceManager.GetString("Anchorable_BtnAutoHide_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Anchorable_BtnClose_Hint {
            get {
                return ResourceManager.GetString("Anchorable_BtnClose_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position.
        /// </summary>
        public static string Anchorable_CxMenu_Hint {
            get {
                return ResourceManager.GetString("Anchorable_CxMenu_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string Anchorable_Dock {
            get {
                return ResourceManager.GetString("Anchorable_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock as Tabbed Document.
        /// </summary>
        public static string Anchorable_DockAsDocument {
            get {
                return ResourceManager.GetString("Anchorable_DockAsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Anchorable_DetachToWindow {
            get {
                return ResourceManager.GetString("Anchorable_DetachToWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        public static string Anchorable_Float {
            get {
                return ResourceManager.GetString("Anchorable_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Anchorable_Hide {
            get {
                return ResourceManager.GetString("Anchorable_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Pin status.
        /// </summary>
        public static string Document_BtnPinned_Hint {
            get {
                return ResourceManager.GetString("Document_BtnPinned_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Document_Close {
            get {
                return ResourceManager.GetString("Document_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All.
        /// </summary>
        public static string Document_CloseAll {
            get {
                return ResourceManager.GetString("Document_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All But This.
        /// </summary>
        public static string Document_CloseAllButThis {
            get {
                return ResourceManager.GetString("Document_CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position.
        /// </summary>
        public static string Document_CxMenu_Hint {
            get {
                return ResourceManager.GetString("Document_CxMenu_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock as Tabbed Document.
        /// </summary>
        public static string Document_DockAsDocument {
            get {
                return ResourceManager.GetString("Document_DockAsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        public static string Document_Float {
            get {
                return ResourceManager.GetString("Document_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Next Tab Group.
        /// </summary>
        public static string Document_MoveToNextTabGroup {
            get {
                return ResourceManager.GetString("Document_MoveToNextTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move To Previous Tab Group.
        /// </summary>
        public static string Document_MoveToPreviousTabGroup {
            get {
                return ResourceManager.GetString("Document_MoveToPreviousTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Horizontal Tab Group.
        /// </summary>
        public static string Document_NewHorizontalTabGroup {
            get {
                return ResourceManager.GetString("Document_NewHorizontalTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Vertical Tab Group.
        /// </summary>
        public static string Document_NewVerticalTabGroup {
            get {
                return ResourceManager.GetString("Document_NewVerticalTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto hide tool.
        /// </summary>
        public static string A11y_AutoHideTool {
            get {
                return ResourceManager.GetString("A11y_AutoHideTool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide tool.
        /// </summary>
        public static string A11y_HideTool {
            get {
                return ResourceManager.GetString("A11y_HideTool", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dock left.
        /// </summary>
        public static string A11y_DockLeft {
            get {
                return ResourceManager.GetString("A11y_DockLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dock top.
        /// </summary>
        public static string A11y_DockTop {
            get {
                return ResourceManager.GetString("A11y_DockTop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dock right.
        /// </summary>
        public static string A11y_DockRight {
            get {
                return ResourceManager.GetString("A11y_DockRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dock bottom.
        /// </summary>
        public static string A11y_DockBottom {
            get {
                return ResourceManager.GetString("A11y_DockBottom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dock inside.
        /// </summary>
        public static string A11y_DockInside {
            get {
                return ResourceManager.GetString("A11y_DockInside", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dock left as tool pane.
        /// </summary>
        public static string A11y_DockLeftAsToolPane {
            get {
                return ResourceManager.GetString("A11y_DockLeftAsToolPane", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dock top as tool pane.
        /// </summary>
        public static string A11y_DockTopAsToolPane {
            get {
                return ResourceManager.GetString("A11y_DockTopAsToolPane", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dock right as tool pane.
        /// </summary>
        public static string A11y_DockRightAsToolPane {
            get {
                return ResourceManager.GetString("A11y_DockRightAsToolPane", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dock bottom as tool pane.
        /// </summary>
        public static string A11y_DockBottomAsToolPane {
            get {
                return ResourceManager.GetString("A11y_DockBottomAsToolPane", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move To.
        /// </summary>
        public static string Toggle_MoveTo {
            get {
                return ResourceManager.GetString("Toggle_MoveTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View Mode.
        /// </summary>
        public static string Toggle_ViewMode {
            get {
                return ResourceManager.GetString("Toggle_ViewMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Docked.
        /// </summary>
        public static string Toggle_Docked {
            get {
                return ResourceManager.GetString("Toggle_Docked", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Toggle_Hidden {
            get {
                return ResourceManager.GetString("Toggle_Hidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Toggle_Options {
            get {
                return ResourceManager.GetString("Toggle_Options", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Toggle_Minimize {
            get {
                return ResourceManager.GetString("Toggle_Minimize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Hidden Tool Windows.
        /// </summary>
        public static string Toggle_ShowHiddenToolWindows {
            get {
                return ResourceManager.GetString("Toggle_ShowHiddenToolWindows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Left Top.
        /// </summary>
        public static string Toggle_Zone_LeftTop {
            get {
                return ResourceManager.GetString("Toggle_Zone_LeftTop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Left Bottom.
        /// </summary>
        public static string Toggle_Zone_LeftBottom {
            get {
                return ResourceManager.GetString("Toggle_Zone_LeftBottom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right Top.
        /// </summary>
        public static string Toggle_Zone_RightTop {
            get {
                return ResourceManager.GetString("Toggle_Zone_RightTop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Right Bottom.
        /// </summary>
        public static string Toggle_Zone_RightBottom {
            get {
                return ResourceManager.GetString("Toggle_Zone_RightBottom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        public static string Toggle_Zone_BottomLeft {
            get {
                return ResourceManager.GetString("Toggle_Zone_BottomLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        public static string Toggle_Zone_BottomRight {
            get {
                return ResourceManager.GetString("Toggle_Zone_BottomRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Window_Maximize {
            get {
                return ResourceManager.GetString("Window_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Window_Restore {
            get {
                return ResourceManager.GetString("Window_Restore", resourceCulture);
            }
        }
    }
}